name: upi_payment_flutter
version: 0.0.3
description: A Flutter package to simplify UPI-based payment integration.
homepage: https://github.com/aslisubhash/Futter-UPI-Payment
# author: Subhash Chaudhary <subhash@digitalkumbh.in>

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
